services:
  centreon:
    build: .
    container_name: centreon
    ports:
      - "80:80"
    privileged: true
    volumes:
      - centreon-conf:/etc/centreon
    networks:
      tfg:
        ipv4_address: 10.0.0.10
        aliases:
          - centreon
  mariadb:
    container_name: mariadb
    build: ./centreon-database
    ports:
      - "3306:3306"
    privileged: true
    networks:
      tfg:
        ipv4_address: 10.0.0.20
        aliases:
          - mariadb
    volumes:
      - centreon-db:/var/lib/mysql
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    privileged: true
    volumes:
      - grafana-provisioning:/var/lib/grafana
    networks:
      tfg:
        ipv4_address: 10.0.0.30
        aliases:
          - grafana
networks:
  tfg:
    ipam:
        config:
          - subnet: "10.0.0.0/24"
volumes:
  centreon-conf:
  centreon-db:
  grafana-config:
  grafana-provisioning:
