version: '3.8'
services:
  centreon:
    image: rubentg98/centreon:1.0
    container_name: centreon
    ports:
      - "80:80"
    privileged: true
    volumes:
      - centreon-config:/etc/centreon
    networks:
      tfg:
        ipv4_address: 10.0.0.10
        aliases:
          - centreon
  mariadb:
    container_name: mariadb
    image: rubentg98/centreon-database:1.0
    ports:
      - "3306:3306"
    privileged: true
    networks:
      tfg:
        ipv4_address: 10.0.0.20
        aliases:
          - mariadb
    volumes:
      - centreon-db:/var/lib/mysql
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:8.5.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-config:/var/lib/grafana
    networks:
      tfg:
        ipv4_address: 10.0.0.30
        aliases:
          - grafana
networks:
  tfg:
    ipam:
        config:
          - subnet: "10.0.0.0/24"
volumes:
  centreon-config:
    external: true
  centreon-db:
    external: true
  grafana-config:
    external: true
